# Generated by Django 4.2.7 on 2023-11-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_product_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
